### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by maresb** [synapticarbors/pixi2ces#1]
I don't see this yet on conda-forge. It'd be great to add some installation instructions to the README.

**Comment by synapticarbors** [comment]
Since this is a prototype that I threw together after looking at the `pixi-pack` code, I wasn't sure if I was going to make an official release. Certainly if there is interest, I'd be happy to look into it though.

**Comment by maresb** [comment]
I'd definitely like to play around with it, particularly in the context of using it to replace `conda-lock install`.

I'm unfortunately not yet proficient in rust. (It's certainly in my overwhelmingly-long todo-list though!) So some pointers on which commands to run would be very helpful.

**Comment by synapticarbors** [comment]
I'm a novice with rust as well -- basically I've just written a few small tools/libraries and done Advent of Code with it. Assuming you have the rust tool chain on your machine via rustup, after you clone this repo, you can run the tool from the `pixi2ces` directory like:

```
cargo run -- /path_to_pixi_project/pixi.toml -e cuda -p linux-64
```

That would then dump the file `conda-linux-64-cuda.lock` to the current directory. Let me know if you run into any issues or have additional questions.
